[package]
name = "common_programming_concepts"
version = "0.1.0"
authors = ["Davide Caputo <dave.caputo93@gmail.com>"]
edition = "2018"
default-run = "main"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
